###############################################################################
## SPORTS2D PROJECT PARAMETERS                                               ##
###############################################################################

[project]
video_input = 'cam2.mp4'
px_to_m_from_person_id = 0
px_to_m_person_height = 1.75
visible_side = ['auto']
load_trc_px = ''
compare = false
time_range = []
video_dir = ''
webcam_id = 0
input_size = [1280, 720]

[process]
multiperson = true
show_realtime_results = true
save_vid = true
save_img = false
save_pose = true
calculate_angles = true
save_angles = true
result_dir = ''

[pose]
slowmo_factor = 1
pose_model = 'Body_with_feet'
mode = 'balanced'
det_frequency = 4
device = 'auto'
backend = 'auto'
tracking_mode = 'sports2d'
keypoint_likelihood_threshold = 0.3
average_likelihood_threshold = 0.5
keypoint_number_threshold = 0.3

[px_to_meters_conversion]
to_meters = true
make_c3d = true
save_calib = true
floor_angle = 'auto'
xy_origin = ['auto']
calib_file = ''

[angles]
display_angle_values_on = ['body', 'list']
fontSize = 0.3
joint_angles = ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip', 'Right shoulder', 'Left shoulder', 'Right elbow', 'Left elbow', 'Right wrist', 'Left wrist']
segment_angles = ['Right foot', 'Left foot', 'Right shank', 'Left shank', 'Right thigh', 'Left thigh', 'Pelvis', 'Trunk', 'Shoulders', 'Head', 'Right arm', 'Left arm', 'Right forearm', 'Left forearm']
flip_left_right = true
correct_segment_angles_with_floor_angle = true

[post-processing]
interpolate = true
interp_gap_smaller_than = 10
fill_large_gaps_with = 'last_value'
filter = true
show_graphs = true
filter_type = 'butterworth'
   [post-processing.butterworth]
   order = 4 
   cut_off_frequency = 6
   [post-processing.gaussian]
   sigma_kernel = 1
   [post-processing.loess]
   nb_values_used = 5
   [post-processing.median]
   kernel_size = 3

[kinematics]
do_ik = true
use_augmentation = true
use_contacts_muscles = true
participant_mass = [67.0, 55.0]
right_left_symmetry = true
default_height = 1.7
fastest_frames_to_remove_percent = 0.1
close_to_zero_speed_px = 50
close_to_zero_speed_m = 0.2
large_hip_knee_angles = 45
trimmed_extrema_percent = 0.5
remove_individual_scaling_setup = true
remove_individual_ik_setup = true

[logging]
use_custom_logging = false

[pose.CUSTOM]
name = "Hip"
id = 19
  [[pose.CUSTOM.children]]
  name = "RHip"
  id = 12
     [[pose.CUSTOM.children.children]]
     name = "RKnee"
     id = 14
        [[pose.CUSTOM.children.children.children]]
        name = "RAnkle"
        id = 16
           [[pose.CUSTOM.children.children.children.children]]
           name = "RBigToe"
           id = 21
              [[pose.CUSTOM.children.children.children.children.children]]
              name = "RSmallToe"
              id = 23
           [[pose.CUSTOM.children.children.children.children]]
           name = "RHeel"
           id = 25
  [[pose.CUSTOM.children]]
  name = "LHip"
  id = 11
     [[pose.CUSTOM.children.children]]
     name = "LKnee"
     id = 13
        [[pose.CUSTOM.children.children.children]]
        name = "LAnkle"
        id = 15
           [[pose.CUSTOM.children.children.children.children]]
           name = "LBigToe"
           id = 20
              [[pose.CUSTOM.children.children.children.children.children]]
              name = "LSmallToe"
              id = 22
           [[pose.CUSTOM.children.children.children.children]]
           name = "LHeel"
           id = 24
  [[pose.CUSTOM.children]]
  name = "Neck"
  id = 18
     [[pose.CUSTOM.children.children]]
     name = "Head"
     id = 17
        [[pose.CUSTOM.children.children.children]]
        name = "Nose"
        id = 0
     [[pose.CUSTOM.children.children]]
     name = "RShoulder"
     id = 6
        [[pose.CUSTOM.children.children.children]]
        name = "RElbow"
        id = 8
           [[pose.CUSTOM.children.children.children.children]]
           name = "RWrist"
           id = 10
     [[pose.CUSTOM.children.children]]
     name = "LShoulder"
     id = 5
        [[pose.CUSTOM.children.children.children]]
        name = "LElbow"
        id = 7
           [[pose.CUSTOM.children.children.children.children]]
           name = "LWrist"
           id = 9